apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    name: test-pod-label
spec:
  containers:
  - name: kubernetes-pause
    image: quay.io/jfclere/fedora:myhttpd
    command:
    - mod_kubernetes
    - tomcat

